jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use a supported Ruby version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.8"

      # Install GitHub Pages (includes Jekyll + Cayman theme + all whitelisted plugins)
      - name: Install GitHub Pages gem
        run: |
          gem install github-pages

      # Build your site into ./_site
      - name: Build site
        run: jekyll build --destination ./_site

      # Debug: list what got built
      - name: List built files
        run: ls -R _site

      # Upload the built folder for deployment
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4