name: Build & Deploy Jekyll site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.8"

      # 3. Install the GitHub Pages gem (includes jekyll + theme + plugins)
      - run: |
          gem install bundler
          echo 'gem "github-pages", group: :jekyll_plugins' > Gemfile
          bundle install

      # 4. Build the site into ./_site
      - run: bundle exec jekyll build --destination ./_site

      # 5. Verify the build output (optional debug)
      - run: ls -R _site

      # 6. Upload the built `_site` folder as the Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 7. Deploy the artifact to GitHub Pages
      - uses: actions/deploy-pages@v4